services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=comics_v3
    volumes:
      - comics_v3_data:/bitnami/postgresql

volumes:
  comics_v3_data:
